box = "generic/centos8"

shared_localpath = "."
shared_vmpath = "/shared"


master_name = "zamazzalServer"

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.ssh.forward_agent = true
  config.vm.synced_folder shared_localpath, shared_vmpath, type: 'virtualbox'

  config.vm.provision "shell", path: "scripts/firewalld-disable.sh"
  config.vm.provision "shell", path: "scripts/k3s-install.sh"

  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /shared/confs
  SHELL

  config.vm.define master_name do |master|
    master.vm.hostname = master_name
    master.vm.network "public_network", use_dhcp_assigned_default_route: true
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 3
      vb.name = master_name
    end

    master.vm.provision "up", type: "shell", run: "always", inline: <<-SHELL
    nohup /usr/local/bin/k3s server --write-kubeconfig /shared/confs/kubeconfig --write-kubeconfig-mode 644 --node-name zamazzalS --flannel-iface eth1 >> /var/log/k3s-server.log 2>&1 & 
    SHELL

    master.vm.provision "shell", inline: <<-SHELL
    NODE_TOKEN="/var/lib/rancher/k3s/server/node-token"
    while [ ! -e ${NODE_TOKEN} ]
    do
      echo "Waiting for node token..."
      sleep 1
    done
    cp ${NODE_TOKEN} /shared/confs/master1-token
    SHELL

    master.vm.provision "shell", path: "scripts/kubectl-install.sh"

    master.vm.provision "shell", inline: <<-SHELL
    /usr/local/bin/kubectl create namespace gitlab
    cp /shared/confs/gitlab.yaml .
	  sed -i "s/YOURIP/$(ifconfig eth1 | awk '/inet / {print $2}')/g" gitlab.yaml
	  /usr/local/bin/kubectl apply -f gitlab.yaml
    /usr/local/bin/kubectl rollout status deployment gitlab -n gitlab
    echo -n "addr: "
	  ifconfig eth1 | awk '/inet / {print $2}'
    echo "port: 8081"
    SHELL

  end
end
