box = "generic/centos8"

shared_localpath = "."
shared_vmpath = "/shared"


master_name = "zamazzalServer"

Vagrant.configure("2") do |config|
  config.vm.box = box
  config.ssh.forward_agent = true
  config.vm.synced_folder shared_localpath, shared_vmpath, type: 'virtualbox'

  config.vm.provision "shell", path: "scripts/firewalld-disable.sh"

  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /shared/confs
  SHELL

  config.vm.define master_name do |master|
    master.vm.hostname = master_name
    master.vm.network "public_network", use_dhcp_assigned_default_route: true
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 3
      vb.name = master_name
    end

    master.vm.provision "shell", path: "scripts/docker-install.sh"

    master.vm.provision "up", type: "shell", run: "always", inline: <<-SHELL
    systemctl start docker

    docker run --detach \
    --hostname gitlab.1337.com \
    --publish 443:443 --publish 8081:80 --publish 2222:22 \
    --name gitlab \
    --restart always \
    --volume $GITLAB_HOME/config:/etc/gitlab:Z \
    --volume $GITLAB_HOME/logs:/var/log/gitlab:Z \
    --volume $GITLAB_HOME/data:/var/opt/gitlab:Z \
    gitlab/gitlab-ce:latest

    docker exec gitlab update-permissions
  
    SHELL
  end
end
